#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include "libchess.ph"

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 31), // int()(char *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 8), // char *
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION, 31), // int()(char *, size_t)
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  5 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28), // size_t
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  7 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/*  8 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/*  9 */ _CFFI_OP(_CFFI_OP_ARRAY, 11), // char[8][9]
/* 10 */ (_cffi_opcode_t)(8),
/* 11 */ _CFFI_OP(_CFFI_OP_ARRAY, 8), // char[9]
/* 12 */ (_cffi_opcode_t)(9),
/* 13 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // enum Antidiagonals
/* 14 */ _CFFI_OP(_CFFI_OP_ENUM, 1), // enum CastlingRightsEnum
/* 15 */ _CFFI_OP(_CFFI_OP_ENUM, 2), // enum CastlingSide
/* 16 */ _CFFI_OP(_CFFI_OP_ENUM, 3), // enum Color
/* 17 */ _CFFI_OP(_CFFI_OP_ENUM, 4), // enum Diagonals
/* 18 */ _CFFI_OP(_CFFI_OP_ENUM, 5), // enum Files
/* 19 */ _CFFI_OP(_CFFI_OP_ARRAY, 18), // enum Files[2]
/* 20 */ (_cffi_opcode_t)(2),
/* 21 */ _CFFI_OP(_CFFI_OP_ARRAY, 19), // enum Files[2][2]
/* 22 */ (_cffi_opcode_t)(2),
/* 23 */ _CFFI_OP(_CFFI_OP_ENUM, 6), // enum MoveType
/* 24 */ _CFFI_OP(_CFFI_OP_ENUM, 7), // enum PieceLetter
/* 25 */ _CFFI_OP(_CFFI_OP_ENUM, 8), // enum PieceName
/* 26 */ _CFFI_OP(_CFFI_OP_ENUM, 9), // enum PieceType
/* 27 */ _CFFI_OP(_CFFI_OP_ENUM, 10), // enum ProblemType
/* 28 */ _CFFI_OP(_CFFI_OP_ENUM, 11), // enum PromoLetter
/* 29 */ _CFFI_OP(_CFFI_OP_ENUM, 12), // enum Ranks
/* 30 */ _CFFI_OP(_CFFI_OP_ENUM, 13), // enum SquareName
/* 31 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 32 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // struct Fen
/* 33 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 6), // unsigned short
};

static int _cffi_const_AntidiagonalA1A1(unsigned long long *o)
{
  int n = (AntidiagonalA1A1) <= 0;
  *o = (unsigned long long)((AntidiagonalA1A1) | 0);  /* check that AntidiagonalA1A1 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalA2B1(unsigned long long *o)
{
  int n = (AntidiagonalA2B1) <= 0;
  *o = (unsigned long long)((AntidiagonalA2B1) | 0);  /* check that AntidiagonalA2B1 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalA3C1(unsigned long long *o)
{
  int n = (AntidiagonalA3C1) <= 0;
  *o = (unsigned long long)((AntidiagonalA3C1) | 0);  /* check that AntidiagonalA3C1 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalA4D1(unsigned long long *o)
{
  int n = (AntidiagonalA4D1) <= 0;
  *o = (unsigned long long)((AntidiagonalA4D1) | 0);  /* check that AntidiagonalA4D1 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalA5E1(unsigned long long *o)
{
  int n = (AntidiagonalA5E1) <= 0;
  *o = (unsigned long long)((AntidiagonalA5E1) | 0);  /* check that AntidiagonalA5E1 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalA6F1(unsigned long long *o)
{
  int n = (AntidiagonalA6F1) <= 0;
  *o = (unsigned long long)((AntidiagonalA6F1) | 0);  /* check that AntidiagonalA6F1 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalA7G1(unsigned long long *o)
{
  int n = (AntidiagonalA7G1) <= 0;
  *o = (unsigned long long)((AntidiagonalA7G1) | 0);  /* check that AntidiagonalA7G1 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalA8H1(unsigned long long *o)
{
  int n = (AntidiagonalA8H1) <= 0;
  *o = (unsigned long long)((AntidiagonalA8H1) | 0);  /* check that AntidiagonalA8H1 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalB8H2(unsigned long long *o)
{
  int n = (AntidiagonalB8H2) <= 0;
  *o = (unsigned long long)((AntidiagonalB8H2) | 0);  /* check that AntidiagonalB8H2 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalC8H3(unsigned long long *o)
{
  int n = (AntidiagonalC8H3) <= 0;
  *o = (unsigned long long)((AntidiagonalC8H3) | 0);  /* check that AntidiagonalC8H3 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalD8H4(unsigned long long *o)
{
  int n = (AntidiagonalD8H4) <= 0;
  *o = (unsigned long long)((AntidiagonalD8H4) | 0);  /* check that AntidiagonalD8H4 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalE8H5(unsigned long long *o)
{
  int n = (AntidiagonalE8H5) <= 0;
  *o = (unsigned long long)((AntidiagonalE8H5) | 0);  /* check that AntidiagonalE8H5 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalF8H6(unsigned long long *o)
{
  int n = (AntidiagonalF8H6) <= 0;
  *o = (unsigned long long)((AntidiagonalF8H6) | 0);  /* check that AntidiagonalF8H6 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalG8H7(unsigned long long *o)
{
  int n = (AntidiagonalG8H7) <= 0;
  *o = (unsigned long long)((AntidiagonalG8H7) | 0);  /* check that AntidiagonalG8H7 is an integer */
  return n;
}

static int _cffi_const_AntidiagonalH8H8(unsigned long long *o)
{
  int n = (AntidiagonalH8H8) <= 0;
  *o = (unsigned long long)((AntidiagonalH8H8) | 0);  /* check that AntidiagonalH8H8 is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteNoneBlackNone(unsigned long long *o)
{
  int n = (CastlingRightsWhiteNoneBlackNone) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteNoneBlackNone) | 0);  /* check that CastlingRightsWhiteNoneBlackNone is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteNoneBlackKingside(unsigned long long *o)
{
  int n = (CastlingRightsWhiteNoneBlackKingside) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteNoneBlackKingside) | 0);  /* check that CastlingRightsWhiteNoneBlackKingside is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteNoneBlackQueenside(unsigned long long *o)
{
  int n = (CastlingRightsWhiteNoneBlackQueenside) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteNoneBlackQueenside) | 0);  /* check that CastlingRightsWhiteNoneBlackQueenside is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteNoneBlackBoth(unsigned long long *o)
{
  int n = (CastlingRightsWhiteNoneBlackBoth) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteNoneBlackBoth) | 0);  /* check that CastlingRightsWhiteNoneBlackBoth is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteKingsideBlackNone(unsigned long long *o)
{
  int n = (CastlingRightsWhiteKingsideBlackNone) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteKingsideBlackNone) | 0);  /* check that CastlingRightsWhiteKingsideBlackNone is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteQueensideBlackNone(unsigned long long *o)
{
  int n = (CastlingRightsWhiteQueensideBlackNone) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteQueensideBlackNone) | 0);  /* check that CastlingRightsWhiteQueensideBlackNone is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteBothBlackNone(unsigned long long *o)
{
  int n = (CastlingRightsWhiteBothBlackNone) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteBothBlackNone) | 0);  /* check that CastlingRightsWhiteBothBlackNone is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteKingsideBlackKingside(unsigned long long *o)
{
  int n = (CastlingRightsWhiteKingsideBlackKingside) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteKingsideBlackKingside) | 0);  /* check that CastlingRightsWhiteKingsideBlackKingside is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteQueensideBlackKingside(unsigned long long *o)
{
  int n = (CastlingRightsWhiteQueensideBlackKingside) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteQueensideBlackKingside) | 0);  /* check that CastlingRightsWhiteQueensideBlackKingside is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteBothBlackKingside(unsigned long long *o)
{
  int n = (CastlingRightsWhiteBothBlackKingside) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteBothBlackKingside) | 0);  /* check that CastlingRightsWhiteBothBlackKingside is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteKingsideBlackQueenside(unsigned long long *o)
{
  int n = (CastlingRightsWhiteKingsideBlackQueenside) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteKingsideBlackQueenside) | 0);  /* check that CastlingRightsWhiteKingsideBlackQueenside is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteQueensideBlackQueenside(unsigned long long *o)
{
  int n = (CastlingRightsWhiteQueensideBlackQueenside) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteQueensideBlackQueenside) | 0);  /* check that CastlingRightsWhiteQueensideBlackQueenside is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteBothBlackQueenside(unsigned long long *o)
{
  int n = (CastlingRightsWhiteBothBlackQueenside) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteBothBlackQueenside) | 0);  /* check that CastlingRightsWhiteBothBlackQueenside is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteKingsideBlackBoth(unsigned long long *o)
{
  int n = (CastlingRightsWhiteKingsideBlackBoth) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteKingsideBlackBoth) | 0);  /* check that CastlingRightsWhiteKingsideBlackBoth is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteQueensideBlackBoth(unsigned long long *o)
{
  int n = (CastlingRightsWhiteQueensideBlackBoth) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteQueensideBlackBoth) | 0);  /* check that CastlingRightsWhiteQueensideBlackBoth is an integer */
  return n;
}

static int _cffi_const_CastlingRightsWhiteBothBlackBoth(unsigned long long *o)
{
  int n = (CastlingRightsWhiteBothBlackBoth) <= 0;
  *o = (unsigned long long)((CastlingRightsWhiteBothBlackBoth) | 0);  /* check that CastlingRightsWhiteBothBlackBoth is an integer */
  return n;
}

static int _cffi_const_CastlingSideNone(unsigned long long *o)
{
  int n = (CastlingSideNone) <= 0;
  *o = (unsigned long long)((CastlingSideNone) | 0);  /* check that CastlingSideNone is an integer */
  return n;
}

static int _cffi_const_CastlingSideKingside(unsigned long long *o)
{
  int n = (CastlingSideKingside) <= 0;
  *o = (unsigned long long)((CastlingSideKingside) | 0);  /* check that CastlingSideKingside is an integer */
  return n;
}

static int _cffi_const_CastlingSideQueenside(unsigned long long *o)
{
  int n = (CastlingSideQueenside) <= 0;
  *o = (unsigned long long)((CastlingSideQueenside) | 0);  /* check that CastlingSideQueenside is an integer */
  return n;
}

static int _cffi_const_CastlingSideBoth(unsigned long long *o)
{
  int n = (CastlingSideBoth) <= 0;
  *o = (unsigned long long)((CastlingSideBoth) | 0);  /* check that CastlingSideBoth is an integer */
  return n;
}

static int _cffi_const_ColorWhite(unsigned long long *o)
{
  int n = (ColorWhite) <= 0;
  *o = (unsigned long long)((ColorWhite) | 0);  /* check that ColorWhite is an integer */
  return n;
}

static int _cffi_const_ColorBlack(unsigned long long *o)
{
  int n = (ColorBlack) <= 0;
  *o = (unsigned long long)((ColorBlack) | 0);  /* check that ColorBlack is an integer */
  return n;
}

static int _cffi_const_DiagonalH1H1(unsigned long long *o)
{
  int n = (DiagonalH1H1) <= 0;
  *o = (unsigned long long)((DiagonalH1H1) | 0);  /* check that DiagonalH1H1 is an integer */
  return n;
}

static int _cffi_const_DiagonalG1H2(unsigned long long *o)
{
  int n = (DiagonalG1H2) <= 0;
  *o = (unsigned long long)((DiagonalG1H2) | 0);  /* check that DiagonalG1H2 is an integer */
  return n;
}

static int _cffi_const_DiagonalF1H3(unsigned long long *o)
{
  int n = (DiagonalF1H3) <= 0;
  *o = (unsigned long long)((DiagonalF1H3) | 0);  /* check that DiagonalF1H3 is an integer */
  return n;
}

static int _cffi_const_DiagonalE1H4(unsigned long long *o)
{
  int n = (DiagonalE1H4) <= 0;
  *o = (unsigned long long)((DiagonalE1H4) | 0);  /* check that DiagonalE1H4 is an integer */
  return n;
}

static int _cffi_const_DiagonalD1H5(unsigned long long *o)
{
  int n = (DiagonalD1H5) <= 0;
  *o = (unsigned long long)((DiagonalD1H5) | 0);  /* check that DiagonalD1H5 is an integer */
  return n;
}

static int _cffi_const_DiagonalC1H6(unsigned long long *o)
{
  int n = (DiagonalC1H6) <= 0;
  *o = (unsigned long long)((DiagonalC1H6) | 0);  /* check that DiagonalC1H6 is an integer */
  return n;
}

static int _cffi_const_DiagonalB1H7(unsigned long long *o)
{
  int n = (DiagonalB1H7) <= 0;
  *o = (unsigned long long)((DiagonalB1H7) | 0);  /* check that DiagonalB1H7 is an integer */
  return n;
}

static int _cffi_const_DiagonalA1H8(unsigned long long *o)
{
  int n = (DiagonalA1H8) <= 0;
  *o = (unsigned long long)((DiagonalA1H8) | 0);  /* check that DiagonalA1H8 is an integer */
  return n;
}

static int _cffi_const_DiagonalA2G8(unsigned long long *o)
{
  int n = (DiagonalA2G8) <= 0;
  *o = (unsigned long long)((DiagonalA2G8) | 0);  /* check that DiagonalA2G8 is an integer */
  return n;
}

static int _cffi_const_DiagonalA3F8(unsigned long long *o)
{
  int n = (DiagonalA3F8) <= 0;
  *o = (unsigned long long)((DiagonalA3F8) | 0);  /* check that DiagonalA3F8 is an integer */
  return n;
}

static int _cffi_const_DiagonalA4E8(unsigned long long *o)
{
  int n = (DiagonalA4E8) <= 0;
  *o = (unsigned long long)((DiagonalA4E8) | 0);  /* check that DiagonalA4E8 is an integer */
  return n;
}

static int _cffi_const_DiagonalA5D8(unsigned long long *o)
{
  int n = (DiagonalA5D8) <= 0;
  *o = (unsigned long long)((DiagonalA5D8) | 0);  /* check that DiagonalA5D8 is an integer */
  return n;
}

static int _cffi_const_DiagonalA6C8(unsigned long long *o)
{
  int n = (DiagonalA6C8) <= 0;
  *o = (unsigned long long)((DiagonalA6C8) | 0);  /* check that DiagonalA6C8 is an integer */
  return n;
}

static int _cffi_const_DiagonalA7B8(unsigned long long *o)
{
  int n = (DiagonalA7B8) <= 0;
  *o = (unsigned long long)((DiagonalA7B8) | 0);  /* check that DiagonalA7B8 is an integer */
  return n;
}

static int _cffi_const_DiagonalA8A8(unsigned long long *o)
{
  int n = (DiagonalA8A8) <= 0;
  *o = (unsigned long long)((DiagonalA8A8) | 0);  /* check that DiagonalA8A8 is an integer */
  return n;
}

static int _cffi_const_FileA(unsigned long long *o)
{
  int n = (FileA) <= 0;
  *o = (unsigned long long)((FileA) | 0);  /* check that FileA is an integer */
  return n;
}

static int _cffi_const_FileB(unsigned long long *o)
{
  int n = (FileB) <= 0;
  *o = (unsigned long long)((FileB) | 0);  /* check that FileB is an integer */
  return n;
}

static int _cffi_const_FileC(unsigned long long *o)
{
  int n = (FileC) <= 0;
  *o = (unsigned long long)((FileC) | 0);  /* check that FileC is an integer */
  return n;
}

static int _cffi_const_FileD(unsigned long long *o)
{
  int n = (FileD) <= 0;
  *o = (unsigned long long)((FileD) | 0);  /* check that FileD is an integer */
  return n;
}

static int _cffi_const_FileE(unsigned long long *o)
{
  int n = (FileE) <= 0;
  *o = (unsigned long long)((FileE) | 0);  /* check that FileE is an integer */
  return n;
}

static int _cffi_const_FileF(unsigned long long *o)
{
  int n = (FileF) <= 0;
  *o = (unsigned long long)((FileF) | 0);  /* check that FileF is an integer */
  return n;
}

static int _cffi_const_FileG(unsigned long long *o)
{
  int n = (FileG) <= 0;
  *o = (unsigned long long)((FileG) | 0);  /* check that FileG is an integer */
  return n;
}

static int _cffi_const_FileH(unsigned long long *o)
{
  int n = (FileH) <= 0;
  *o = (unsigned long long)((FileH) | 0);  /* check that FileH is an integer */
  return n;
}

static int _cffi_const_FileNone(unsigned long long *o)
{
  int n = (FileNone) <= 0;
  *o = (unsigned long long)((FileNone) | 0);  /* check that FileNone is an integer */
  return n;
}

static int _cffi_const_MoveTypeNormal(unsigned long long *o)
{
  int n = (MoveTypeNormal) <= 0;
  *o = (unsigned long long)((MoveTypeNormal) | 0);  /* check that MoveTypeNormal is an integer */
  return n;
}

static int _cffi_const_MoveTypeValid(unsigned long long *o)
{
  int n = (MoveTypeValid) <= 0;
  *o = (unsigned long long)((MoveTypeValid) | 0);  /* check that MoveTypeValid is an integer */
  return n;
}

static int _cffi_const_MoveTypeCapture(unsigned long long *o)
{
  int n = (MoveTypeCapture) <= 0;
  *o = (unsigned long long)((MoveTypeCapture) | 0);  /* check that MoveTypeCapture is an integer */
  return n;
}

static int _cffi_const_MoveTypeCastlingKingside(unsigned long long *o)
{
  int n = (MoveTypeCastlingKingside) <= 0;
  *o = (unsigned long long)((MoveTypeCastlingKingside) | 0);  /* check that MoveTypeCastlingKingside is an integer */
  return n;
}

static int _cffi_const_MoveTypeCastlingQueenside(unsigned long long *o)
{
  int n = (MoveTypeCastlingQueenside) <= 0;
  *o = (unsigned long long)((MoveTypeCastlingQueenside) | 0);  /* check that MoveTypeCastlingQueenside is an integer */
  return n;
}

static int _cffi_const_MoveTypePromotion(unsigned long long *o)
{
  int n = (MoveTypePromotion) <= 0;
  *o = (unsigned long long)((MoveTypePromotion) | 0);  /* check that MoveTypePromotion is an integer */
  return n;
}

static int _cffi_const_MoveTypeEnPassant(unsigned long long *o)
{
  int n = (MoveTypeEnPassant) <= 0;
  *o = (unsigned long long)((MoveTypeEnPassant) | 0);  /* check that MoveTypeEnPassant is an integer */
  return n;
}

static int _cffi_const_MoveTypeNull(unsigned long long *o)
{
  int n = (MoveTypeNull) <= 0;
  *o = (unsigned long long)((MoveTypeNull) | 0);  /* check that MoveTypeNull is an integer */
  return n;
}

static int _cffi_const_PieceLetter_e(unsigned long long *o)
{
  int n = (PieceLetter_e) <= 0;
  *o = (unsigned long long)((PieceLetter_e) | 0);  /* check that PieceLetter_e is an integer */
  return n;
}

static int _cffi_const_PieceLetter_P(unsigned long long *o)
{
  int n = (PieceLetter_P) <= 0;
  *o = (unsigned long long)((PieceLetter_P) | 0);  /* check that PieceLetter_P is an integer */
  return n;
}

static int _cffi_const_PieceLetter_N(unsigned long long *o)
{
  int n = (PieceLetter_N) <= 0;
  *o = (unsigned long long)((PieceLetter_N) | 0);  /* check that PieceLetter_N is an integer */
  return n;
}

static int _cffi_const_PieceLetter_B(unsigned long long *o)
{
  int n = (PieceLetter_B) <= 0;
  *o = (unsigned long long)((PieceLetter_B) | 0);  /* check that PieceLetter_B is an integer */
  return n;
}

static int _cffi_const_PieceLetter_R(unsigned long long *o)
{
  int n = (PieceLetter_R) <= 0;
  *o = (unsigned long long)((PieceLetter_R) | 0);  /* check that PieceLetter_R is an integer */
  return n;
}

static int _cffi_const_PieceLetter_Q(unsigned long long *o)
{
  int n = (PieceLetter_Q) <= 0;
  *o = (unsigned long long)((PieceLetter_Q) | 0);  /* check that PieceLetter_Q is an integer */
  return n;
}

static int _cffi_const_PieceLetter_K(unsigned long long *o)
{
  int n = (PieceLetter_K) <= 0;
  *o = (unsigned long long)((PieceLetter_K) | 0);  /* check that PieceLetter_K is an integer */
  return n;
}

static int _cffi_const_PieceLetter_X(unsigned long long *o)
{
  int n = (PieceLetter_X) <= 0;
  *o = (unsigned long long)((PieceLetter_X) | 0);  /* check that PieceLetter_X is an integer */
  return n;
}

static int _cffi_const_PieceLetter_O(unsigned long long *o)
{
  int n = (PieceLetter_O) <= 0;
  *o = (unsigned long long)((PieceLetter_O) | 0);  /* check that PieceLetter_O is an integer */
  return n;
}

static int _cffi_const_PieceLetter_p(unsigned long long *o)
{
  int n = (PieceLetter_p) <= 0;
  *o = (unsigned long long)((PieceLetter_p) | 0);  /* check that PieceLetter_p is an integer */
  return n;
}

static int _cffi_const_PieceLetter_n(unsigned long long *o)
{
  int n = (PieceLetter_n) <= 0;
  *o = (unsigned long long)((PieceLetter_n) | 0);  /* check that PieceLetter_n is an integer */
  return n;
}

static int _cffi_const_PieceLetter_b(unsigned long long *o)
{
  int n = (PieceLetter_b) <= 0;
  *o = (unsigned long long)((PieceLetter_b) | 0);  /* check that PieceLetter_b is an integer */
  return n;
}

static int _cffi_const_PieceLetter_r(unsigned long long *o)
{
  int n = (PieceLetter_r) <= 0;
  *o = (unsigned long long)((PieceLetter_r) | 0);  /* check that PieceLetter_r is an integer */
  return n;
}

static int _cffi_const_PieceLetter_q(unsigned long long *o)
{
  int n = (PieceLetter_q) <= 0;
  *o = (unsigned long long)((PieceLetter_q) | 0);  /* check that PieceLetter_q is an integer */
  return n;
}

static int _cffi_const_PieceLetter_k(unsigned long long *o)
{
  int n = (PieceLetter_k) <= 0;
  *o = (unsigned long long)((PieceLetter_k) | 0);  /* check that PieceLetter_k is an integer */
  return n;
}

static int _cffi_const_PieceLetter_x(unsigned long long *o)
{
  int n = (PieceLetter_x) <= 0;
  *o = (unsigned long long)((PieceLetter_x) | 0);  /* check that PieceLetter_x is an integer */
  return n;
}

static int _cffi_const_PieceNameNone(unsigned long long *o)
{
  int n = (PieceNameNone) <= 0;
  *o = (unsigned long long)((PieceNameNone) | 0);  /* check that PieceNameNone is an integer */
  return n;
}

static int _cffi_const_WhitePawn(unsigned long long *o)
{
  int n = (WhitePawn) <= 0;
  *o = (unsigned long long)((WhitePawn) | 0);  /* check that WhitePawn is an integer */
  return n;
}

static int _cffi_const_WhiteKnight(unsigned long long *o)
{
  int n = (WhiteKnight) <= 0;
  *o = (unsigned long long)((WhiteKnight) | 0);  /* check that WhiteKnight is an integer */
  return n;
}

static int _cffi_const_WhiteBishop(unsigned long long *o)
{
  int n = (WhiteBishop) <= 0;
  *o = (unsigned long long)((WhiteBishop) | 0);  /* check that WhiteBishop is an integer */
  return n;
}

static int _cffi_const_WhiteRook(unsigned long long *o)
{
  int n = (WhiteRook) <= 0;
  *o = (unsigned long long)((WhiteRook) | 0);  /* check that WhiteRook is an integer */
  return n;
}

static int _cffi_const_WhiteQueen(unsigned long long *o)
{
  int n = (WhiteQueen) <= 0;
  *o = (unsigned long long)((WhiteQueen) | 0);  /* check that WhiteQueen is an integer */
  return n;
}

static int _cffi_const_WhiteKing(unsigned long long *o)
{
  int n = (WhiteKing) <= 0;
  *o = (unsigned long long)((WhiteKing) | 0);  /* check that WhiteKing is an integer */
  return n;
}

static int _cffi_const_PieceNameWhite(unsigned long long *o)
{
  int n = (PieceNameWhite) <= 0;
  *o = (unsigned long long)((PieceNameWhite) | 0);  /* check that PieceNameWhite is an integer */
  return n;
}

static int _cffi_const_PieceNameAny(unsigned long long *o)
{
  int n = (PieceNameAny) <= 0;
  *o = (unsigned long long)((PieceNameAny) | 0);  /* check that PieceNameAny is an integer */
  return n;
}

static int _cffi_const_BlackPawn(unsigned long long *o)
{
  int n = (BlackPawn) <= 0;
  *o = (unsigned long long)((BlackPawn) | 0);  /* check that BlackPawn is an integer */
  return n;
}

static int _cffi_const_BlackKnight(unsigned long long *o)
{
  int n = (BlackKnight) <= 0;
  *o = (unsigned long long)((BlackKnight) | 0);  /* check that BlackKnight is an integer */
  return n;
}

static int _cffi_const_BlackBishop(unsigned long long *o)
{
  int n = (BlackBishop) <= 0;
  *o = (unsigned long long)((BlackBishop) | 0);  /* check that BlackBishop is an integer */
  return n;
}

static int _cffi_const_BlackRook(unsigned long long *o)
{
  int n = (BlackRook) <= 0;
  *o = (unsigned long long)((BlackRook) | 0);  /* check that BlackRook is an integer */
  return n;
}

static int _cffi_const_BlackQueen(unsigned long long *o)
{
  int n = (BlackQueen) <= 0;
  *o = (unsigned long long)((BlackQueen) | 0);  /* check that BlackQueen is an integer */
  return n;
}

static int _cffi_const_BlackKing(unsigned long long *o)
{
  int n = (BlackKing) <= 0;
  *o = (unsigned long long)((BlackKing) | 0);  /* check that BlackKing is an integer */
  return n;
}

static int _cffi_const_PieceNameBlack(unsigned long long *o)
{
  int n = (PieceNameBlack) <= 0;
  *o = (unsigned long long)((PieceNameBlack) | 0);  /* check that PieceNameBlack is an integer */
  return n;
}

static int _cffi_const_PieceTypeNone(unsigned long long *o)
{
  int n = (PieceTypeNone) <= 0;
  *o = (unsigned long long)((PieceTypeNone) | 0);  /* check that PieceTypeNone is an integer */
  return n;
}

static int _cffi_const_Pawn(unsigned long long *o)
{
  int n = (Pawn) <= 0;
  *o = (unsigned long long)((Pawn) | 0);  /* check that Pawn is an integer */
  return n;
}

static int _cffi_const_Knight(unsigned long long *o)
{
  int n = (Knight) <= 0;
  *o = (unsigned long long)((Knight) | 0);  /* check that Knight is an integer */
  return n;
}

static int _cffi_const_Bishop(unsigned long long *o)
{
  int n = (Bishop) <= 0;
  *o = (unsigned long long)((Bishop) | 0);  /* check that Bishop is an integer */
  return n;
}

static int _cffi_const_Rook(unsigned long long *o)
{
  int n = (Rook) <= 0;
  *o = (unsigned long long)((Rook) | 0);  /* check that Rook is an integer */
  return n;
}

static int _cffi_const_Queen(unsigned long long *o)
{
  int n = (Queen) <= 0;
  *o = (unsigned long long)((Queen) | 0);  /* check that Queen is an integer */
  return n;
}

static int _cffi_const_King(unsigned long long *o)
{
  int n = (King) <= 0;
  *o = (unsigned long long)((King) | 0);  /* check that King is an integer */
  return n;
}

static int _cffi_const_PieceTypeAny(unsigned long long *o)
{
  int n = (PieceTypeAny) <= 0;
  *o = (unsigned long long)((PieceTypeAny) | 0);  /* check that PieceTypeAny is an integer */
  return n;
}

static int _cffi_const_ProblemTypeNone(unsigned long long *o)
{
  int n = (ProblemTypeNone) <= 0;
  *o = (unsigned long long)((ProblemTypeNone) | 0);  /* check that ProblemTypeNone is an integer */
  return n;
}

static int _cffi_const_ProblemTypeBestMove(unsigned long long *o)
{
  int n = (ProblemTypeBestMove) <= 0;
  *o = (unsigned long long)((ProblemTypeBestMove) | 0);  /* check that ProblemTypeBestMove is an integer */
  return n;
}

static int _cffi_const_ProblemTypeAvoidMove(unsigned long long *o)
{
  int n = (ProblemTypeAvoidMove) <= 0;
  *o = (unsigned long long)((ProblemTypeAvoidMove) | 0);  /* check that ProblemTypeAvoidMove is an integer */
  return n;
}

static int _cffi_const_PromoLetter_n(unsigned long long *o)
{
  int n = (PromoLetter_n) <= 0;
  *o = (unsigned long long)((PromoLetter_n) | 0);  /* check that PromoLetter_n is an integer */
  return n;
}

static int _cffi_const_PromoLetter_b(unsigned long long *o)
{
  int n = (PromoLetter_b) <= 0;
  *o = (unsigned long long)((PromoLetter_b) | 0);  /* check that PromoLetter_b is an integer */
  return n;
}

static int _cffi_const_PromoLetter_r(unsigned long long *o)
{
  int n = (PromoLetter_r) <= 0;
  *o = (unsigned long long)((PromoLetter_r) | 0);  /* check that PromoLetter_r is an integer */
  return n;
}

static int _cffi_const_PromoLetter_q(unsigned long long *o)
{
  int n = (PromoLetter_q) <= 0;
  *o = (unsigned long long)((PromoLetter_q) | 0);  /* check that PromoLetter_q is an integer */
  return n;
}

static int _cffi_const_Rank1(unsigned long long *o)
{
  int n = (Rank1) <= 0;
  *o = (unsigned long long)((Rank1) | 0);  /* check that Rank1 is an integer */
  return n;
}

static int _cffi_const_Rank2(unsigned long long *o)
{
  int n = (Rank2) <= 0;
  *o = (unsigned long long)((Rank2) | 0);  /* check that Rank2 is an integer */
  return n;
}

static int _cffi_const_Rank3(unsigned long long *o)
{
  int n = (Rank3) <= 0;
  *o = (unsigned long long)((Rank3) | 0);  /* check that Rank3 is an integer */
  return n;
}

static int _cffi_const_Rank4(unsigned long long *o)
{
  int n = (Rank4) <= 0;
  *o = (unsigned long long)((Rank4) | 0);  /* check that Rank4 is an integer */
  return n;
}

static int _cffi_const_Rank5(unsigned long long *o)
{
  int n = (Rank5) <= 0;
  *o = (unsigned long long)((Rank5) | 0);  /* check that Rank5 is an integer */
  return n;
}

static int _cffi_const_Rank6(unsigned long long *o)
{
  int n = (Rank6) <= 0;
  *o = (unsigned long long)((Rank6) | 0);  /* check that Rank6 is an integer */
  return n;
}

static int _cffi_const_Rank7(unsigned long long *o)
{
  int n = (Rank7) <= 0;
  *o = (unsigned long long)((Rank7) | 0);  /* check that Rank7 is an integer */
  return n;
}

static int _cffi_const_Rank8(unsigned long long *o)
{
  int n = (Rank8) <= 0;
  *o = (unsigned long long)((Rank8) | 0);  /* check that Rank8 is an integer */
  return n;
}

static int _cffi_const_RankNone(unsigned long long *o)
{
  int n = (RankNone) <= 0;
  *o = (unsigned long long)((RankNone) | 0);  /* check that RankNone is an integer */
  return n;
}

static int _cffi_const_SquareA1(unsigned long long *o)
{
  int n = (SquareA1) <= 0;
  *o = (unsigned long long)((SquareA1) | 0);  /* check that SquareA1 is an integer */
  return n;
}

static int _cffi_const_SquareB1(unsigned long long *o)
{
  int n = (SquareB1) <= 0;
  *o = (unsigned long long)((SquareB1) | 0);  /* check that SquareB1 is an integer */
  return n;
}

static int _cffi_const_SquareC1(unsigned long long *o)
{
  int n = (SquareC1) <= 0;
  *o = (unsigned long long)((SquareC1) | 0);  /* check that SquareC1 is an integer */
  return n;
}

static int _cffi_const_SquareD1(unsigned long long *o)
{
  int n = (SquareD1) <= 0;
  *o = (unsigned long long)((SquareD1) | 0);  /* check that SquareD1 is an integer */
  return n;
}

static int _cffi_const_SquareE1(unsigned long long *o)
{
  int n = (SquareE1) <= 0;
  *o = (unsigned long long)((SquareE1) | 0);  /* check that SquareE1 is an integer */
  return n;
}

static int _cffi_const_SquareF1(unsigned long long *o)
{
  int n = (SquareF1) <= 0;
  *o = (unsigned long long)((SquareF1) | 0);  /* check that SquareF1 is an integer */
  return n;
}

static int _cffi_const_SquareG1(unsigned long long *o)
{
  int n = (SquareG1) <= 0;
  *o = (unsigned long long)((SquareG1) | 0);  /* check that SquareG1 is an integer */
  return n;
}

static int _cffi_const_SquareH1(unsigned long long *o)
{
  int n = (SquareH1) <= 0;
  *o = (unsigned long long)((SquareH1) | 0);  /* check that SquareH1 is an integer */
  return n;
}

static int _cffi_const_SquareA2(unsigned long long *o)
{
  int n = (SquareA2) <= 0;
  *o = (unsigned long long)((SquareA2) | 0);  /* check that SquareA2 is an integer */
  return n;
}

static int _cffi_const_SquareB2(unsigned long long *o)
{
  int n = (SquareB2) <= 0;
  *o = (unsigned long long)((SquareB2) | 0);  /* check that SquareB2 is an integer */
  return n;
}

static int _cffi_const_SquareC2(unsigned long long *o)
{
  int n = (SquareC2) <= 0;
  *o = (unsigned long long)((SquareC2) | 0);  /* check that SquareC2 is an integer */
  return n;
}

static int _cffi_const_SquareD2(unsigned long long *o)
{
  int n = (SquareD2) <= 0;
  *o = (unsigned long long)((SquareD2) | 0);  /* check that SquareD2 is an integer */
  return n;
}

static int _cffi_const_SquareE2(unsigned long long *o)
{
  int n = (SquareE2) <= 0;
  *o = (unsigned long long)((SquareE2) | 0);  /* check that SquareE2 is an integer */
  return n;
}

static int _cffi_const_SquareF2(unsigned long long *o)
{
  int n = (SquareF2) <= 0;
  *o = (unsigned long long)((SquareF2) | 0);  /* check that SquareF2 is an integer */
  return n;
}

static int _cffi_const_SquareG2(unsigned long long *o)
{
  int n = (SquareG2) <= 0;
  *o = (unsigned long long)((SquareG2) | 0);  /* check that SquareG2 is an integer */
  return n;
}

static int _cffi_const_SquareH2(unsigned long long *o)
{
  int n = (SquareH2) <= 0;
  *o = (unsigned long long)((SquareH2) | 0);  /* check that SquareH2 is an integer */
  return n;
}

static int _cffi_const_SquareA3(unsigned long long *o)
{
  int n = (SquareA3) <= 0;
  *o = (unsigned long long)((SquareA3) | 0);  /* check that SquareA3 is an integer */
  return n;
}

static int _cffi_const_SquareB3(unsigned long long *o)
{
  int n = (SquareB3) <= 0;
  *o = (unsigned long long)((SquareB3) | 0);  /* check that SquareB3 is an integer */
  return n;
}

static int _cffi_const_SquareC3(unsigned long long *o)
{
  int n = (SquareC3) <= 0;
  *o = (unsigned long long)((SquareC3) | 0);  /* check that SquareC3 is an integer */
  return n;
}

static int _cffi_const_SquareD3(unsigned long long *o)
{
  int n = (SquareD3) <= 0;
  *o = (unsigned long long)((SquareD3) | 0);  /* check that SquareD3 is an integer */
  return n;
}

static int _cffi_const_SquareE3(unsigned long long *o)
{
  int n = (SquareE3) <= 0;
  *o = (unsigned long long)((SquareE3) | 0);  /* check that SquareE3 is an integer */
  return n;
}

static int _cffi_const_SquareF3(unsigned long long *o)
{
  int n = (SquareF3) <= 0;
  *o = (unsigned long long)((SquareF3) | 0);  /* check that SquareF3 is an integer */
  return n;
}

static int _cffi_const_SquareG3(unsigned long long *o)
{
  int n = (SquareG3) <= 0;
  *o = (unsigned long long)((SquareG3) | 0);  /* check that SquareG3 is an integer */
  return n;
}

static int _cffi_const_SquareH3(unsigned long long *o)
{
  int n = (SquareH3) <= 0;
  *o = (unsigned long long)((SquareH3) | 0);  /* check that SquareH3 is an integer */
  return n;
}

static int _cffi_const_SquareA4(unsigned long long *o)
{
  int n = (SquareA4) <= 0;
  *o = (unsigned long long)((SquareA4) | 0);  /* check that SquareA4 is an integer */
  return n;
}

static int _cffi_const_SquareB4(unsigned long long *o)
{
  int n = (SquareB4) <= 0;
  *o = (unsigned long long)((SquareB4) | 0);  /* check that SquareB4 is an integer */
  return n;
}

static int _cffi_const_SquareC4(unsigned long long *o)
{
  int n = (SquareC4) <= 0;
  *o = (unsigned long long)((SquareC4) | 0);  /* check that SquareC4 is an integer */
  return n;
}

static int _cffi_const_SquareD4(unsigned long long *o)
{
  int n = (SquareD4) <= 0;
  *o = (unsigned long long)((SquareD4) | 0);  /* check that SquareD4 is an integer */
  return n;
}

static int _cffi_const_SquareE4(unsigned long long *o)
{
  int n = (SquareE4) <= 0;
  *o = (unsigned long long)((SquareE4) | 0);  /* check that SquareE4 is an integer */
  return n;
}

static int _cffi_const_SquareF4(unsigned long long *o)
{
  int n = (SquareF4) <= 0;
  *o = (unsigned long long)((SquareF4) | 0);  /* check that SquareF4 is an integer */
  return n;
}

static int _cffi_const_SquareG4(unsigned long long *o)
{
  int n = (SquareG4) <= 0;
  *o = (unsigned long long)((SquareG4) | 0);  /* check that SquareG4 is an integer */
  return n;
}

static int _cffi_const_SquareH4(unsigned long long *o)
{
  int n = (SquareH4) <= 0;
  *o = (unsigned long long)((SquareH4) | 0);  /* check that SquareH4 is an integer */
  return n;
}

static int _cffi_const_SquareA5(unsigned long long *o)
{
  int n = (SquareA5) <= 0;
  *o = (unsigned long long)((SquareA5) | 0);  /* check that SquareA5 is an integer */
  return n;
}

static int _cffi_const_SquareB5(unsigned long long *o)
{
  int n = (SquareB5) <= 0;
  *o = (unsigned long long)((SquareB5) | 0);  /* check that SquareB5 is an integer */
  return n;
}

static int _cffi_const_SquareC5(unsigned long long *o)
{
  int n = (SquareC5) <= 0;
  *o = (unsigned long long)((SquareC5) | 0);  /* check that SquareC5 is an integer */
  return n;
}

static int _cffi_const_SquareD5(unsigned long long *o)
{
  int n = (SquareD5) <= 0;
  *o = (unsigned long long)((SquareD5) | 0);  /* check that SquareD5 is an integer */
  return n;
}

static int _cffi_const_SquareE5(unsigned long long *o)
{
  int n = (SquareE5) <= 0;
  *o = (unsigned long long)((SquareE5) | 0);  /* check that SquareE5 is an integer */
  return n;
}

static int _cffi_const_SquareF5(unsigned long long *o)
{
  int n = (SquareF5) <= 0;
  *o = (unsigned long long)((SquareF5) | 0);  /* check that SquareF5 is an integer */
  return n;
}

static int _cffi_const_SquareG5(unsigned long long *o)
{
  int n = (SquareG5) <= 0;
  *o = (unsigned long long)((SquareG5) | 0);  /* check that SquareG5 is an integer */
  return n;
}

static int _cffi_const_SquareH5(unsigned long long *o)
{
  int n = (SquareH5) <= 0;
  *o = (unsigned long long)((SquareH5) | 0);  /* check that SquareH5 is an integer */
  return n;
}

static int _cffi_const_SquareA6(unsigned long long *o)
{
  int n = (SquareA6) <= 0;
  *o = (unsigned long long)((SquareA6) | 0);  /* check that SquareA6 is an integer */
  return n;
}

static int _cffi_const_SquareB6(unsigned long long *o)
{
  int n = (SquareB6) <= 0;
  *o = (unsigned long long)((SquareB6) | 0);  /* check that SquareB6 is an integer */
  return n;
}

static int _cffi_const_SquareC6(unsigned long long *o)
{
  int n = (SquareC6) <= 0;
  *o = (unsigned long long)((SquareC6) | 0);  /* check that SquareC6 is an integer */
  return n;
}

static int _cffi_const_SquareD6(unsigned long long *o)
{
  int n = (SquareD6) <= 0;
  *o = (unsigned long long)((SquareD6) | 0);  /* check that SquareD6 is an integer */
  return n;
}

static int _cffi_const_SquareE6(unsigned long long *o)
{
  int n = (SquareE6) <= 0;
  *o = (unsigned long long)((SquareE6) | 0);  /* check that SquareE6 is an integer */
  return n;
}

static int _cffi_const_SquareF6(unsigned long long *o)
{
  int n = (SquareF6) <= 0;
  *o = (unsigned long long)((SquareF6) | 0);  /* check that SquareF6 is an integer */
  return n;
}

static int _cffi_const_SquareG6(unsigned long long *o)
{
  int n = (SquareG6) <= 0;
  *o = (unsigned long long)((SquareG6) | 0);  /* check that SquareG6 is an integer */
  return n;
}

static int _cffi_const_SquareH6(unsigned long long *o)
{
  int n = (SquareH6) <= 0;
  *o = (unsigned long long)((SquareH6) | 0);  /* check that SquareH6 is an integer */
  return n;
}

static int _cffi_const_SquareA7(unsigned long long *o)
{
  int n = (SquareA7) <= 0;
  *o = (unsigned long long)((SquareA7) | 0);  /* check that SquareA7 is an integer */
  return n;
}

static int _cffi_const_SquareB7(unsigned long long *o)
{
  int n = (SquareB7) <= 0;
  *o = (unsigned long long)((SquareB7) | 0);  /* check that SquareB7 is an integer */
  return n;
}

static int _cffi_const_SquareC7(unsigned long long *o)
{
  int n = (SquareC7) <= 0;
  *o = (unsigned long long)((SquareC7) | 0);  /* check that SquareC7 is an integer */
  return n;
}

static int _cffi_const_SquareD7(unsigned long long *o)
{
  int n = (SquareD7) <= 0;
  *o = (unsigned long long)((SquareD7) | 0);  /* check that SquareD7 is an integer */
  return n;
}

static int _cffi_const_SquareE7(unsigned long long *o)
{
  int n = (SquareE7) <= 0;
  *o = (unsigned long long)((SquareE7) | 0);  /* check that SquareE7 is an integer */
  return n;
}

static int _cffi_const_SquareF7(unsigned long long *o)
{
  int n = (SquareF7) <= 0;
  *o = (unsigned long long)((SquareF7) | 0);  /* check that SquareF7 is an integer */
  return n;
}

static int _cffi_const_SquareG7(unsigned long long *o)
{
  int n = (SquareG7) <= 0;
  *o = (unsigned long long)((SquareG7) | 0);  /* check that SquareG7 is an integer */
  return n;
}

static int _cffi_const_SquareH7(unsigned long long *o)
{
  int n = (SquareH7) <= 0;
  *o = (unsigned long long)((SquareH7) | 0);  /* check that SquareH7 is an integer */
  return n;
}

static int _cffi_const_SquareA8(unsigned long long *o)
{
  int n = (SquareA8) <= 0;
  *o = (unsigned long long)((SquareA8) | 0);  /* check that SquareA8 is an integer */
  return n;
}

static int _cffi_const_SquareB8(unsigned long long *o)
{
  int n = (SquareB8) <= 0;
  *o = (unsigned long long)((SquareB8) | 0);  /* check that SquareB8 is an integer */
  return n;
}

static int _cffi_const_SquareC8(unsigned long long *o)
{
  int n = (SquareC8) <= 0;
  *o = (unsigned long long)((SquareC8) | 0);  /* check that SquareC8 is an integer */
  return n;
}

static int _cffi_const_SquareD8(unsigned long long *o)
{
  int n = (SquareD8) <= 0;
  *o = (unsigned long long)((SquareD8) | 0);  /* check that SquareD8 is an integer */
  return n;
}

static int _cffi_const_SquareE8(unsigned long long *o)
{
  int n = (SquareE8) <= 0;
  *o = (unsigned long long)((SquareE8) | 0);  /* check that SquareE8 is an integer */
  return n;
}

static int _cffi_const_SquareF8(unsigned long long *o)
{
  int n = (SquareF8) <= 0;
  *o = (unsigned long long)((SquareF8) | 0);  /* check that SquareF8 is an integer */
  return n;
}

static int _cffi_const_SquareG8(unsigned long long *o)
{
  int n = (SquareG8) <= 0;
  *o = (unsigned long long)((SquareG8) | 0);  /* check that SquareG8 is an integer */
  return n;
}

static int _cffi_const_SquareH8(unsigned long long *o)
{
  int n = (SquareH8) <= 0;
  *o = (unsigned long long)((SquareH8) | 0);  /* check that SquareH8 is an integer */
  return n;
}

static int _cffi_const_SquareNone(unsigned long long *o)
{
  int n = (SquareNone) <= 0;
  *o = (unsigned long long)((SquareNone) | 0);  /* check that SquareNone is an integer */
  return n;
}

static int _cffi_d_fentostr(char * x0, size_t x1)
{
  return fentostr(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fentostr(PyObject *self, PyObject *args)
{
  char * x0;
  size_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "fentostr", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (char *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, size_t);
  if (x1 == (size_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = fentostr(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_fentostr _cffi_d_fentostr
#endif

static int _cffi_d_strtofen(char * x0)
{
  return strtofen(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_strtofen(PyObject *self, PyObject *arg0)
{
  char * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (char *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = strtofen(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_strtofen _cffi_d_strtofen
#endif

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_Fen(struct Fen *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char(*tmp)[8][9] = &p->ranks; (void)tmp; }
  { enum Color *tmp = &p->sideToMove; (void)tmp; }
  { enum CastlingRightsEnum *tmp = &p->castlingRights; (void)tmp; }
  { enum Files *tmp = &p->enPassant; (void)tmp; }
  (void)((p->halfmoveClock) | 0);  /* check that 'struct Fen.halfmoveClock' is an integer */
  (void)((p->moveNumber) | 0);  /* check that 'struct Fen.moveNumber' is an integer */
  (void)((p->isChess960) | 0);  /* check that 'struct Fen.isChess960' is an integer */
  { enum Files(*tmp)[2][2] = &p->castlingRook; (void)tmp; }
}
struct _cffi_align_struct_Fen { char x; struct Fen y; };

static const struct _cffi_global_s _cffi_globals[] = {
  { "AntidiagonalA1A1", (void *)_cffi_const_AntidiagonalA1A1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalA2B1", (void *)_cffi_const_AntidiagonalA2B1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalA3C1", (void *)_cffi_const_AntidiagonalA3C1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalA4D1", (void *)_cffi_const_AntidiagonalA4D1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalA5E1", (void *)_cffi_const_AntidiagonalA5E1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalA6F1", (void *)_cffi_const_AntidiagonalA6F1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalA7G1", (void *)_cffi_const_AntidiagonalA7G1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalA8H1", (void *)_cffi_const_AntidiagonalA8H1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalB8H2", (void *)_cffi_const_AntidiagonalB8H2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalC8H3", (void *)_cffi_const_AntidiagonalC8H3, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalD8H4", (void *)_cffi_const_AntidiagonalD8H4, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalE8H5", (void *)_cffi_const_AntidiagonalE8H5, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalF8H6", (void *)_cffi_const_AntidiagonalF8H6, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalG8H7", (void *)_cffi_const_AntidiagonalG8H7, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "AntidiagonalH8H8", (void *)_cffi_const_AntidiagonalH8H8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Bishop", (void *)_cffi_const_Bishop, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "BlackBishop", (void *)_cffi_const_BlackBishop, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "BlackKing", (void *)_cffi_const_BlackKing, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "BlackKnight", (void *)_cffi_const_BlackKnight, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "BlackPawn", (void *)_cffi_const_BlackPawn, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "BlackQueen", (void *)_cffi_const_BlackQueen, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "BlackRook", (void *)_cffi_const_BlackRook, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteBothBlackBoth", (void *)_cffi_const_CastlingRightsWhiteBothBlackBoth, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteBothBlackKingside", (void *)_cffi_const_CastlingRightsWhiteBothBlackKingside, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteBothBlackNone", (void *)_cffi_const_CastlingRightsWhiteBothBlackNone, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteBothBlackQueenside", (void *)_cffi_const_CastlingRightsWhiteBothBlackQueenside, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteKingsideBlackBoth", (void *)_cffi_const_CastlingRightsWhiteKingsideBlackBoth, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteKingsideBlackKingside", (void *)_cffi_const_CastlingRightsWhiteKingsideBlackKingside, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteKingsideBlackNone", (void *)_cffi_const_CastlingRightsWhiteKingsideBlackNone, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteKingsideBlackQueenside", (void *)_cffi_const_CastlingRightsWhiteKingsideBlackQueenside, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteNoneBlackBoth", (void *)_cffi_const_CastlingRightsWhiteNoneBlackBoth, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteNoneBlackKingside", (void *)_cffi_const_CastlingRightsWhiteNoneBlackKingside, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteNoneBlackNone", (void *)_cffi_const_CastlingRightsWhiteNoneBlackNone, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteNoneBlackQueenside", (void *)_cffi_const_CastlingRightsWhiteNoneBlackQueenside, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteQueensideBlackBoth", (void *)_cffi_const_CastlingRightsWhiteQueensideBlackBoth, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteQueensideBlackKingside", (void *)_cffi_const_CastlingRightsWhiteQueensideBlackKingside, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteQueensideBlackNone", (void *)_cffi_const_CastlingRightsWhiteQueensideBlackNone, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingRightsWhiteQueensideBlackQueenside", (void *)_cffi_const_CastlingRightsWhiteQueensideBlackQueenside, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingSideBoth", (void *)_cffi_const_CastlingSideBoth, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingSideKingside", (void *)_cffi_const_CastlingSideKingside, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingSideNone", (void *)_cffi_const_CastlingSideNone, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "CastlingSideQueenside", (void *)_cffi_const_CastlingSideQueenside, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ColorBlack", (void *)_cffi_const_ColorBlack, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ColorWhite", (void *)_cffi_const_ColorWhite, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalA1H8", (void *)_cffi_const_DiagonalA1H8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalA2G8", (void *)_cffi_const_DiagonalA2G8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalA3F8", (void *)_cffi_const_DiagonalA3F8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalA4E8", (void *)_cffi_const_DiagonalA4E8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalA5D8", (void *)_cffi_const_DiagonalA5D8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalA6C8", (void *)_cffi_const_DiagonalA6C8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalA7B8", (void *)_cffi_const_DiagonalA7B8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalA8A8", (void *)_cffi_const_DiagonalA8A8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalB1H7", (void *)_cffi_const_DiagonalB1H7, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalC1H6", (void *)_cffi_const_DiagonalC1H6, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalD1H5", (void *)_cffi_const_DiagonalD1H5, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalE1H4", (void *)_cffi_const_DiagonalE1H4, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalF1H3", (void *)_cffi_const_DiagonalF1H3, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalG1H2", (void *)_cffi_const_DiagonalG1H2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "DiagonalH1H1", (void *)_cffi_const_DiagonalH1H1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FileA", (void *)_cffi_const_FileA, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FileB", (void *)_cffi_const_FileB, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FileC", (void *)_cffi_const_FileC, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FileD", (void *)_cffi_const_FileD, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FileE", (void *)_cffi_const_FileE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FileF", (void *)_cffi_const_FileF, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FileG", (void *)_cffi_const_FileG, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FileH", (void *)_cffi_const_FileH, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "FileNone", (void *)_cffi_const_FileNone, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "King", (void *)_cffi_const_King, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Knight", (void *)_cffi_const_Knight, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "MoveTypeCapture", (void *)_cffi_const_MoveTypeCapture, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "MoveTypeCastlingKingside", (void *)_cffi_const_MoveTypeCastlingKingside, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "MoveTypeCastlingQueenside", (void *)_cffi_const_MoveTypeCastlingQueenside, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "MoveTypeEnPassant", (void *)_cffi_const_MoveTypeEnPassant, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "MoveTypeNormal", (void *)_cffi_const_MoveTypeNormal, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "MoveTypeNull", (void *)_cffi_const_MoveTypeNull, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "MoveTypePromotion", (void *)_cffi_const_MoveTypePromotion, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "MoveTypeValid", (void *)_cffi_const_MoveTypeValid, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Pawn", (void *)_cffi_const_Pawn, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_B", (void *)_cffi_const_PieceLetter_B, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_K", (void *)_cffi_const_PieceLetter_K, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_N", (void *)_cffi_const_PieceLetter_N, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_O", (void *)_cffi_const_PieceLetter_O, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_P", (void *)_cffi_const_PieceLetter_P, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_Q", (void *)_cffi_const_PieceLetter_Q, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_R", (void *)_cffi_const_PieceLetter_R, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_X", (void *)_cffi_const_PieceLetter_X, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_b", (void *)_cffi_const_PieceLetter_b, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_e", (void *)_cffi_const_PieceLetter_e, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_k", (void *)_cffi_const_PieceLetter_k, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_n", (void *)_cffi_const_PieceLetter_n, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_p", (void *)_cffi_const_PieceLetter_p, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_q", (void *)_cffi_const_PieceLetter_q, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_r", (void *)_cffi_const_PieceLetter_r, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceLetter_x", (void *)_cffi_const_PieceLetter_x, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceNameAny", (void *)_cffi_const_PieceNameAny, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceNameBlack", (void *)_cffi_const_PieceNameBlack, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceNameNone", (void *)_cffi_const_PieceNameNone, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceNameWhite", (void *)_cffi_const_PieceNameWhite, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceTypeAny", (void *)_cffi_const_PieceTypeAny, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PieceTypeNone", (void *)_cffi_const_PieceTypeNone, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ProblemTypeAvoidMove", (void *)_cffi_const_ProblemTypeAvoidMove, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ProblemTypeBestMove", (void *)_cffi_const_ProblemTypeBestMove, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ProblemTypeNone", (void *)_cffi_const_ProblemTypeNone, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PromoLetter_b", (void *)_cffi_const_PromoLetter_b, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PromoLetter_n", (void *)_cffi_const_PromoLetter_n, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PromoLetter_q", (void *)_cffi_const_PromoLetter_q, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "PromoLetter_r", (void *)_cffi_const_PromoLetter_r, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Queen", (void *)_cffi_const_Queen, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Rank1", (void *)_cffi_const_Rank1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Rank2", (void *)_cffi_const_Rank2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Rank3", (void *)_cffi_const_Rank3, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Rank4", (void *)_cffi_const_Rank4, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Rank5", (void *)_cffi_const_Rank5, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Rank6", (void *)_cffi_const_Rank6, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Rank7", (void *)_cffi_const_Rank7, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Rank8", (void *)_cffi_const_Rank8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "RankNone", (void *)_cffi_const_RankNone, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Rook", (void *)_cffi_const_Rook, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareA1", (void *)_cffi_const_SquareA1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareA2", (void *)_cffi_const_SquareA2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareA3", (void *)_cffi_const_SquareA3, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareA4", (void *)_cffi_const_SquareA4, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareA5", (void *)_cffi_const_SquareA5, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareA6", (void *)_cffi_const_SquareA6, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareA7", (void *)_cffi_const_SquareA7, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareA8", (void *)_cffi_const_SquareA8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareB1", (void *)_cffi_const_SquareB1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareB2", (void *)_cffi_const_SquareB2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareB3", (void *)_cffi_const_SquareB3, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareB4", (void *)_cffi_const_SquareB4, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareB5", (void *)_cffi_const_SquareB5, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareB6", (void *)_cffi_const_SquareB6, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareB7", (void *)_cffi_const_SquareB7, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareB8", (void *)_cffi_const_SquareB8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareC1", (void *)_cffi_const_SquareC1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareC2", (void *)_cffi_const_SquareC2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareC3", (void *)_cffi_const_SquareC3, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareC4", (void *)_cffi_const_SquareC4, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareC5", (void *)_cffi_const_SquareC5, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareC6", (void *)_cffi_const_SquareC6, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareC7", (void *)_cffi_const_SquareC7, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareC8", (void *)_cffi_const_SquareC8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareD1", (void *)_cffi_const_SquareD1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareD2", (void *)_cffi_const_SquareD2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareD3", (void *)_cffi_const_SquareD3, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareD4", (void *)_cffi_const_SquareD4, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareD5", (void *)_cffi_const_SquareD5, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareD6", (void *)_cffi_const_SquareD6, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareD7", (void *)_cffi_const_SquareD7, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareD8", (void *)_cffi_const_SquareD8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareE1", (void *)_cffi_const_SquareE1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareE2", (void *)_cffi_const_SquareE2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareE3", (void *)_cffi_const_SquareE3, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareE4", (void *)_cffi_const_SquareE4, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareE5", (void *)_cffi_const_SquareE5, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareE6", (void *)_cffi_const_SquareE6, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareE7", (void *)_cffi_const_SquareE7, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareE8", (void *)_cffi_const_SquareE8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareF1", (void *)_cffi_const_SquareF1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareF2", (void *)_cffi_const_SquareF2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareF3", (void *)_cffi_const_SquareF3, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareF4", (void *)_cffi_const_SquareF4, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareF5", (void *)_cffi_const_SquareF5, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareF6", (void *)_cffi_const_SquareF6, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareF7", (void *)_cffi_const_SquareF7, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareF8", (void *)_cffi_const_SquareF8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareG1", (void *)_cffi_const_SquareG1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareG2", (void *)_cffi_const_SquareG2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareG3", (void *)_cffi_const_SquareG3, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareG4", (void *)_cffi_const_SquareG4, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareG5", (void *)_cffi_const_SquareG5, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareG6", (void *)_cffi_const_SquareG6, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareG7", (void *)_cffi_const_SquareG7, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareG8", (void *)_cffi_const_SquareG8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareH1", (void *)_cffi_const_SquareH1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareH2", (void *)_cffi_const_SquareH2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareH3", (void *)_cffi_const_SquareH3, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareH4", (void *)_cffi_const_SquareH4, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareH5", (void *)_cffi_const_SquareH5, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareH6", (void *)_cffi_const_SquareH6, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareH7", (void *)_cffi_const_SquareH7, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareH8", (void *)_cffi_const_SquareH8, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "SquareNone", (void *)_cffi_const_SquareNone, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "WhiteBishop", (void *)_cffi_const_WhiteBishop, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "WhiteKing", (void *)_cffi_const_WhiteKing, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "WhiteKnight", (void *)_cffi_const_WhiteKnight, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "WhitePawn", (void *)_cffi_const_WhitePawn, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "WhiteQueen", (void *)_cffi_const_WhiteQueen, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "WhiteRook", (void *)_cffi_const_WhiteRook, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "fentostr", (void *)_cffi_f_fentostr, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 3), (void *)_cffi_d_fentostr },
  { "strtofen", (void *)_cffi_f_strtofen, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 0), (void *)_cffi_d_strtofen },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "ranks", offsetof(struct Fen, ranks),
             sizeof(((struct Fen *)0)->ranks),
             _CFFI_OP(_CFFI_OP_NOOP, 9) },
  { "sideToMove", offsetof(struct Fen, sideToMove),
                  sizeof(((struct Fen *)0)->sideToMove),
                  _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "castlingRights", offsetof(struct Fen, castlingRights),
                      sizeof(((struct Fen *)0)->castlingRights),
                      _CFFI_OP(_CFFI_OP_NOOP, 14) },
  { "enPassant", offsetof(struct Fen, enPassant),
                 sizeof(((struct Fen *)0)->enPassant),
                 _CFFI_OP(_CFFI_OP_NOOP, 18) },
  { "halfmoveClock", offsetof(struct Fen, halfmoveClock),
                     sizeof(((struct Fen *)0)->halfmoveClock),
                     _CFFI_OP(_CFFI_OP_NOOP, 33) },
  { "moveNumber", offsetof(struct Fen, moveNumber),
                  sizeof(((struct Fen *)0)->moveNumber),
                  _CFFI_OP(_CFFI_OP_NOOP, 33) },
  { "isChess960", offsetof(struct Fen, isChess960),
                  sizeof(((struct Fen *)0)->isChess960),
                  _CFFI_OP(_CFFI_OP_NOOP, 7) },
  { "castlingRook", offsetof(struct Fen, castlingRook),
                    sizeof(((struct Fen *)0)->castlingRook),
                    _CFFI_OP(_CFFI_OP_NOOP, 21) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "Fen", 32, _CFFI_F_CHECK_FIELDS,
    sizeof(struct Fen), offsetof(struct _cffi_align_struct_Fen, y), 0, 8 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "Antidiagonals", 13, _cffi_prim_int(sizeof(enum Antidiagonals), ((enum Antidiagonals)-1) <= 0),
    "AntidiagonalA1A1,AntidiagonalA2B1,AntidiagonalA3C1,AntidiagonalA4D1,AntidiagonalA5E1,AntidiagonalA6F1,AntidiagonalA7G1,AntidiagonalA8H1,AntidiagonalB8H2,AntidiagonalC8H3,AntidiagonalD8H4,AntidiagonalE8H5,AntidiagonalF8H6,AntidiagonalG8H7,AntidiagonalH8H8" },
  { "CastlingRightsEnum", 14, _cffi_prim_int(sizeof(enum CastlingRightsEnum), ((enum CastlingRightsEnum)-1) <= 0),
    "CastlingRightsWhiteNoneBlackNone,CastlingRightsWhiteNoneBlackKingside,CastlingRightsWhiteNoneBlackQueenside,CastlingRightsWhiteNoneBlackBoth,CastlingRightsWhiteKingsideBlackNone,CastlingRightsWhiteQueensideBlackNone,CastlingRightsWhiteBothBlackNone,CastlingRightsWhiteKingsideBlackKingside,CastlingRightsWhiteQueensideBlackKingside,CastlingRightsWhiteBothBlackKingside,CastlingRightsWhiteKingsideBlackQueenside,CastlingRightsWhiteQueensideBlackQueenside,CastlingRightsWhiteBothBlackQueenside,CastlingRightsWhiteKingsideBlackBoth,CastlingRightsWhiteQueensideBlackBoth,CastlingRightsWhiteBothBlackBoth" },
  { "CastlingSide", 15, _cffi_prim_int(sizeof(enum CastlingSide), ((enum CastlingSide)-1) <= 0),
    "CastlingSideNone,CastlingSideKingside,CastlingSideQueenside,CastlingSideBoth" },
  { "Color", 16, _cffi_prim_int(sizeof(enum Color), ((enum Color)-1) <= 0),
    "ColorWhite,ColorBlack" },
  { "Diagonals", 17, _cffi_prim_int(sizeof(enum Diagonals), ((enum Diagonals)-1) <= 0),
    "DiagonalH1H1,DiagonalG1H2,DiagonalF1H3,DiagonalE1H4,DiagonalD1H5,DiagonalC1H6,DiagonalB1H7,DiagonalA1H8,DiagonalA2G8,DiagonalA3F8,DiagonalA4E8,DiagonalA5D8,DiagonalA6C8,DiagonalA7B8,DiagonalA8A8" },
  { "Files", 18, _cffi_prim_int(sizeof(enum Files), ((enum Files)-1) <= 0),
    "FileA,FileB,FileC,FileD,FileE,FileF,FileG,FileH,FileNone" },
  { "MoveType", 23, _cffi_prim_int(sizeof(enum MoveType), ((enum MoveType)-1) <= 0),
    "MoveTypeNormal,MoveTypeValid,MoveTypeCapture,MoveTypeCastlingKingside,MoveTypeCastlingQueenside,MoveTypePromotion,MoveTypeEnPassant,MoveTypeNull" },
  { "PieceLetter", 24, _cffi_prim_int(sizeof(enum PieceLetter), ((enum PieceLetter)-1) <= 0),
    "PieceLetter_e,PieceLetter_P,PieceLetter_N,PieceLetter_B,PieceLetter_R,PieceLetter_Q,PieceLetter_K,PieceLetter_X,PieceLetter_O,PieceLetter_p,PieceLetter_n,PieceLetter_b,PieceLetter_r,PieceLetter_q,PieceLetter_k,PieceLetter_x" },
  { "PieceName", 25, _cffi_prim_int(sizeof(enum PieceName), ((enum PieceName)-1) <= 0),
    "PieceNameNone,WhitePawn,WhiteKnight,WhiteBishop,WhiteRook,WhiteQueen,WhiteKing,PieceNameWhite,PieceNameAny,BlackPawn,BlackKnight,BlackBishop,BlackRook,BlackQueen,BlackKing,PieceNameBlack" },
  { "PieceType", 26, _cffi_prim_int(sizeof(enum PieceType), ((enum PieceType)-1) <= 0),
    "PieceTypeNone,Pawn,Knight,Bishop,Rook,Queen,King,PieceTypeAny" },
  { "ProblemType", 27, _cffi_prim_int(sizeof(enum ProblemType), ((enum ProblemType)-1) <= 0),
    "ProblemTypeNone,ProblemTypeBestMove,ProblemTypeAvoidMove" },
  { "PromoLetter", 28, _cffi_prim_int(sizeof(enum PromoLetter), ((enum PromoLetter)-1) <= 0),
    "PromoLetter_n,PromoLetter_b,PromoLetter_r,PromoLetter_q" },
  { "Ranks", 29, _cffi_prim_int(sizeof(enum Ranks), ((enum Ranks)-1) <= 0),
    "Rank1,Rank2,Rank3,Rank4,Rank5,Rank6,Rank7,Rank8,RankNone" },
  { "SquareName", 30, _cffi_prim_int(sizeof(enum SquareName), ((enum SquareName)-1) <= 0),
    "SquareA1,SquareB1,SquareC1,SquareD1,SquareE1,SquareF1,SquareG1,SquareH1,SquareA2,SquareB2,SquareC2,SquareD2,SquareE2,SquareF2,SquareG2,SquareH2,SquareA3,SquareB3,SquareC3,SquareD3,SquareE3,SquareF3,SquareG3,SquareH3,SquareA4,SquareB4,SquareC4,SquareD4,SquareE4,SquareF4,SquareG4,SquareH4,SquareA5,SquareB5,SquareC5,SquareD5,SquareE5,SquareF5,SquareG5,SquareH5,SquareA6,SquareB6,SquareC6,SquareD6,SquareE6,SquareF6,SquareG6,SquareH6,SquareA7,SquareB7,SquareC7,SquareD7,SquareE7,SquareF7,SquareG7,SquareH7,SquareA8,SquareB8,SquareC8,SquareD8,SquareE8,SquareF8,SquareG8,SquareH8,SquareNone" },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  NULL,  /* no typenames */
  192,  /* num_globals */
  1,  /* num_struct_unions */
  14,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  34,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_libchess(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_libchess(void) { return NULL; }
#  else
     initlibchess(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_libchess(void)
{
  return _cffi_init("libchess", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initlibchess(void)
{
  _cffi_init("libchess", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
